org: ${file(../common-config.yml):org}
service: ${file(../common-config.yml):service}
app: tucker

frameworkVersion: ">=4"
configValidationMode: ${file(../common-config.yml):configValidationMode}

provider:
  name: aws
  region: ${file(../common-config.yml):region}
  stage: ${opt:stage, 'dev'}
  stackTags:
    app: tucker
    service: front-tucker
  memorySize: 128   # As small as possible
  timeout: 10   # Latency should not be more than 5 s
  stackName: ${self:service}-${self:app}-${self:provider.stage}
  versionFunctions: false

  environment:
    API_STAGE: ${self:provider.stage}
    ACCOUNT_ID: ${aws:accountId}

  #  logRetentionInDays: 15 # CloudWatch log retention period

  # Api Gateway Quota to protect against cost surge.
#  usagePlan:
#    quota:
#      limit: 5000
#      period: MONTH
#    throttle:
#      burstLimit: 50
#      rateLimit: 20

functions:
  - ${file(aws-resources/api-gateway/authorizers.yml)}
  - ${file(aws-resources/api-gateway/agenda-routes.yml)}

plugins:
  - serverless-domain-manager

custom:
#  dynamoDB:
#    classRegistrationTable: "ft-class-registration-table-${self:provider.stage}"

  customDomain:
    domainName: "api.${file(../common-config.yml):domain}"
    stage: ${opt:stage, 'dev'}
    hostedZoneId: Z094454117QPI2R4W783E
    allowPathMatching: true
    certificateName: "*.${file(../common-config.yml):domain}"
    createRoute53Record: true
    endpointType: REGIONAL
    securityPolicy: tls_1_2
    apiType: rest