# Before making change here, make sure to review the cloudformation documentation and see if the changes will cause the table to be dropded and replaced.
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain  # preserve the ressource if the stack is deleted
    Properties:
      BucketName: ${self:custom.distributionBucket}