AgendaGET:
  handler: app/handler/routes/agenda.getAgenda
  events:
    - http:
        path: "/v1/agenda"
        method: GET
        cors: ${file(aws-resources/api-gateway/cors/cors.${opt:stage, 'dev'}.yml):cors}
        authorizer:
          name: jwtAuth
          identitySource: method.request.header.Authorization
          resultTtlInSeconds: 120
          type: request

AgendaPATCH:
  handler: app/handler/routes/agenda.pathAgenda
  events:
    - http:
        path: "/v1/agenda/{registrationId}"
        method: PATCH
        cors: ${file(aws-resources/api-gateway/cors/cors.${opt:stage, 'dev'}.yml):cors}
        authorizer:
          name: jwtAuth
          identitySource: method.request.header.Authorization
          resultTtlInSeconds: 120
          type: request
        request:
          parameters:
            paths:
              registrationId: true