expressApi:
  handler: app/express-api/api.handler
  events:
    - http:
        path: "/v1/agenda"
        method: GET
        cors: ${file(aws-resources/api-gateway/cors/cors.${opt:stage, 'dev'}.yml):cors}
        authorizer:
          name: jwtAuth
          identitySource: method.request.header.Authorization
          resultTtlInSeconds: 120
          type: request