org: ${file(../common-config.yml):org}
service: ${file(../common-config.yml):service}
app: front

frameworkVersion: ">=4"
configValidationMode: ${file(../common-config.yml):configValidationMode}

provider:
  region: us-east-1 # CloudFront associated functions have to be deployed to the us-east-1 region.
  name: aws
  stage: ${opt:stage, 'dev'}
  stackTags:
    app: tucker
    service: front-tucker
  runtime: nodejs22.x
  memorySize: 128 # MB default allocated lambda function memory
  timeout: 15 # Increase Lambda timeout for long-running tasks
  stackName: ${self:service}-${self:app}-${self:provider.stage}
  versionFunctions: false

resources:
  - ${file(aws-resources/s3/s3.yml)}
  - ${file(aws-resources/cloudfront/cloudfront.yml)}

functions:
  cloudfrontHeaders:
    handler: aws-resources/cloudfront/cloudfront.handler
    events:
      - cloudFront:
          eventType: viewer-response
          origin: "s3://${self:custom.distributionBucket}.s3.amazonaws.com"

plugins:
  - serverless-finch

custom:
  distributionBucket: "front-tucker-web-${self:provider.stage}"
  domain:
    dev: "dev.${file(../common-config.yml):domain}"
    prod: "prod.${file(../common-config.yml):domain}"
  client:
    bucketName: ${self:custom.distributionBucket}
    distributionFolder: app/dist/front/browser